- debug: msg=" Attaching disk to VM "
- name: Azure CLI telemetrics off
  command: 'azure telemetry --disable'
- name: Azure Login
  command: "azure login -u {{ ad_username }} -p {{ ad_password }}"
- name: Attach disk to VM
  command: "azure vm disk attach-new -g  {{resource_group_name}} {{item[1]}} {{item[0]}} "
  with_nested:
  - "{{storage_disks}}"
  - "{{storage}}"
